background = "#282828ff"
blend = true
blocks_overlap = 0.0
blocks_r = 6
color = "#fffffffff"
command = "i3status-rs ~/.config/i3status-rust/i3status-rust.toml"
font = "Comic Shanns Mono 13"
height = 20
hide_inactive_tags = true
invert_touchpad_scrolling = true
margin_bottom = 0
margin_left = 8
margin_right = 8
margin_top = 4
position = "top"
separator = "#9a8a62ff"
separator_width = 0
show_mode = true
tag_bg = "#282828ff"
tag_fg = "#bdae93ff"
tag_focused_bg = "#3c3836ff"
tag_focused_fg = "#ebdbb2ff"
#tag_inactive_bg = "#3c3836ff"
#tag_inactive_fg = "#3c3836ff"
#tag_urgent_bg = "#dc8a78ff"
#tag_urgent_fg = "#282828ff"
tags_padding = 15.0
tags_r = 6

[wm.river]
max_tag = 9
